[theme]
primaryColor = "#1a1a1a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1a1a1a"
font = "hhsans-Regular"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
maxMessageSize = 200

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
